#!/bin/sh

DOCKER_MACHINE_IP=$(docker-machine ip default)


CONTAINER_ID=$(docker run -d -p :10022:22 --user root --entrypoint /usr/sbin/sshd mark311/docker-octave-x11-sshd:latest -D)

if [ ! -f .checked ]; then
    expect -c '
spawn ssh -Y -t octave@'$DOCKER_MACHINE_IP' -p10022 octave
expect "no)? "
send "yes\r"
expect "assword:"
send "octave\r"
interact
'
    touch .checked
else   
    expect -c '
spawn ssh -Y -t octave@'$DOCKER_MACHINE_IP' -p10022 octave
expect "assword:"
send "octave\r"
interact
'
fi

docker stop $CONTAINER_ID
docker rm $CONTAINER_ID
