#!/bin/sh

DOCKER_MACHINE_IP=$(docker-machine ip default)

CONTAINER_ID=$(docker run -d -p :10022:22 --user root --entrypoint /usr/sbin/sshd mark311/octave-x11-sshd:v3 -D)

expect -c '
spawn ssh -Y -t octave@'$DOCKER_MACHINE_IP' -p10022 octave
expect "assword:"
send "octave\r"
interact
'

docker stop $CONTAINER_ID
docker rm $CONTAINER_ID
